platform :ios, '7.0'

inhibit_all_warnings!

pod 'AFNetworking', '~> 2.6.3'
pod 'Mantle', '~> 1.5'
pod 'Masonry', '~> 0.5.3'
pod 'FMDB', '~> 2.3'
pod 'LKDBHelper','~> 2.1.1'
pod 'TSMessages', '~> 0.9.9'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SVProgressHUD', '~> 1.0'
pod 'Base64', '~> 1.0.1'
pod 'SDWebImage'
pod 'pop'
pod 'MJRefresh'
pod 'IQKeyboardManager'
pod 'QBImagePickerController'
pod 'GTMBase64', '~> 1.0.0'
